# Generated by Django 4.2.1 on 2023-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Full name")),
                ("email", models.EmailField(max_length=50, verbose_name="User email")),
                ("subject", models.CharField(max_length=50, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "New feedback"), ("P", "Feedback in process"), ("F", "Feedback is finished")],
                        default="N",
                        max_length=1,
                        verbose_name="Feedback status",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Last updated")),
            ],
            options={"verbose_name": "Feedback", "verbose_name_plural": "Feedbacks", "db_table": "feedback"},
        )
    ]
