# Generated by Django 4.2.1 on 2023-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("our_products", "0001_initial")]

    operations = [
        migrations.AddIndex(
            model_name="product", index=models.Index(fields=["id", "slug"], name="our_product_id_82b1db_idx")
        ),
        migrations.AddIndex(
            model_name="product", index=models.Index(fields=["name"], name="our_product_name_09e720_idx")
        ),
        migrations.AddIndex(
            model_name="product", index=models.Index(fields=["-created"], name="our_product_created_2c72b6_idx")
        ),
    ]
