# Generated by Django 4.2.1 on 2023-10-31 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("our_products", "0002_product_our_product_id_82b1db_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))
            ],
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))
            ],
        ),
        migrations.RemoveIndex(model_name="product", name="our_product_id_82b1db_idx"),
        migrations.RemoveIndex(model_name="product", name="our_product_name_09e720_idx"),
        migrations.RemoveIndex(model_name="product", name="our_product_created_2c72b6_idx"),
        migrations.AddField(
            model_name="shoppinglist",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="our_products.product"),
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="our_products.product"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
